#!/bin/sh

##
##  pkgconf - contains necessary definitions and functions for a mkport file
##

PKG_ADD="/usr/5bin/pkgadd -d"
PKG_AD="/usr/5bin/pkgadd"
PKG_RM="/usr/5bin/pkgrm"
PKG_TRANS="/usr/5bin/pkgtrans"
PKG_LOC="/var/spool/pkg"

PORTS_LOC="/usr/ports/"
PKG_CACHE="/var/spool/pkg/"
PKG_LOC="/usr/ports/$CATEGORY/$PKG/"
PKG_PROTO="/usr/5bin/pkgproto"
PKG_MK="/usr/5bin/pkmk"

function mkpkginfo () {
    if [ -f ../pkginfo ]; then
        rm ../pkginfo
        continue
    fi
    if [ ! -f ../pkginfo ]; then
        touch ../pkginfo
        echo "PKG=$PKG" >> ../pkginfo
        echo "NAME=$NAME" >> ../pkginfo
        echo "VERSION=$VERSION" >> ../pkginfo
        echo "ARCH=$ARCH" >> ../pkginfo
        echo "CATEGORY=$CATEGORY" >> ../pkginfo
        echo "PSTAMP=$VERSION" >> ../pkginfo
    fi
}

function extract {
        case "$1" in
            *.tar.bz2|*.tbz2|*.tbz)         tar xvjf "$1" ;;
            *.tgz)                          tar zxvf "$1" ;;
            *.tar.gz)                       tar xvzf "$1" ;;
            *.tar.xz)                       tar xvJf "$1" ;;
            *.tar)                          tar xvf "$1" ;;
            *.rar)                          7z x "$1" ;;
            *.zip)                          unzip "$1" ;;
            *.7z)                           7z x "$1" ;;
            *.lzo)                          lzop -d  "$1" ;;
            *.gz)                           gunzip "$1" ;;
            *.bz2)                          bunzip2 "$1" ;;
            *.Z)                            uncompress "$1" ;;
            *.xz|*.txz|*.lzma|*.tlz)        xz -d "$1" ;;
            *) echo "'$1' could not be decompressed." ;;
        esac
}
