#!/sbin/sh

. /usr/bin/pkg

# Sample mkport with dependencies

# Variables - used to create pkginfo file for pkgmk
pkg="program"
version="1"
category="system"
arch="x86_64"
# adjust if needed
basedir="/"
pstamp="$version"
name="sample mkport"
source="https://urlofsourcecode.com/program-1.tar.gz"
deps="system/dep1 system/dep2 base/dep3 base/dep4"

# This will build all dependencies if they are not currently installed.
# If those have dependencies they will be built as well.
mkdep
# Make tmp directory
mkdir -p /tmp/"$pkg"
# Get source
wget "$source"
# Extract it
tar xf "$pkg"-"$1".tar.gz
# Cd to archive
cd "$pkg"
# prefix=/usr/local should be the default prefix with many programs but use it anyway
./configure --prefix=/usr/local
make
# This creates /tmp/program/usr/local/bin/program - if not change basedir to /usr/local/
DESTDIR=/tmp/"$pkg" make install
# Cd to the tmp directory
cd /tmp/"$pkg"
# Pkgmk creates the package using the generated pkginfo and prototype files.
mkpkg
# /var/spool/pkg/program-1.pkg is created with pkgtrans and can be installed with
# pkg -i program or pkg install program
