#!/bin/sh

. pkg

pkg=libogg
version="1.3.3"
category=audio
arch="x86_64"
basedir="/"
pstamp="$version"
name="Ogg bitstream library"
source="http://downloads.xiph.org/releases/ogg/$pkg-$version.tar.xz"

mkdir -p $pkgtmp

wget "$source"
/bin/tar xf "$pkg"-"$version".tar.xz

cd "$pkg"-$version

./configure --prefix=/usr/local
make
make DESTDIR=/tmp/$pkg install

mkpkg

