#!/usr/5bin/sh -e

. /usr/bin/pkg

pkg=pkgtools
version=0.8.2
category=base
arch="x86_64"
basedir="/usr/bin"
pstamp="$version"
name="frontend for heirloom SVR4 pkgtools"


mkdir -p /tmp/"$pkg"
cd "$pkg"
cp pkg /tmp/"$pkg"
cp pkgbuild /tmp/"$pkg"
cd /tmp/"$pkg"
mkpkg

