#!/sbin/sh

##
## pkg: SVR4 package tools wrapper
##      Uses heirloom sh

## pkgtools
pkg_add="/usr/5bin/pkgadd -d"
pkg_ad="/usr/5bin/pkgadd"
pkg_rm="/usr/5bin/pkgrm"
pkg_trans="/usr/5bin/pkgtrans -s"
pkg_proto="/usr/5bin/pkgproto -c"
pkg_mk="/usr/5bin/pkgmk -o"
pkg_ck="/usr/5bin/pkginfo"

## locations
pkg_loc="/var/spool/pkg"
ports_loc="/usr/ports/"
port_loc="/usr/ports/"$category"/"$pkg""


##
## pkg
##
case "$1" in
	update*|-u*)
        # using heirloom tools to check for root
    	id=`id | awk -F'=' '{print $2}' | awk -F'(' '{print $1}'`
        if [ "$id" != 0 ]
        then
        	echo "You must be root"
        	exit 1
    	elif [ "$id" = 0 ]
        then

        num=`pkg list | wc -l`
        pack=`pkg list | awk '{print $2}'`
        update=`echo "[TODO]"`
        echo "===> There are "$num" packages installed"
        echo "===> "$update" package(s) will be updated:"
        #echo "$pack"
        #ver=`ls "$pkg_loc" | grep "$2" | tail -n1`
        #/usr/5bin/pkgadd -d "$pkg_loc"/"$ver"

        ver_num=`/usr/5bin/pkginfo -x pkgtools |awk 'NR==2{print $2}'`
        #echo "$ver_num"
        fi
    ;;
esac
