#!/usr/5bin/sh -e

. /usr/bin/pkg

# Set Variables -> used to create pkginfo file
pkg="dmenu"
version="4.8"
category="x11"
arch="x86_64"
source="http://dl.suckless.org/tools/$pkg-$version.tar.gz"
basedir="/"
pstamp="$version"
name="dynamic menu"

main() {
    if [ ! -f "$pkg"-"$version".tar.gz ]
    then
        wget "$source"
    fi
    if [ -f "$pkg"-"$version".tar.gz ]
    then
        extract "$pkg"-"$version".tar.gz
        build
    fi
}

build() {

    cd "$pkg"-"$version"

    DESTDIR=/tmp/"$pkg" make install
    cd /tmp/"$pkg"

    mkpkg
}

main
