#!/usr/5bin/sh

##
## pkg: SVR4 package tools wrapper
##      Uses heirloom sh

## pkgtools
pkg_add="/usr/5bin/pkgadd -d"
pkg_ad="/usr/5bin/pkgadd"
pkg_rm="/usr/5bin/pkgrm"
pkg_trans="/usr/5bin/pkgtrans -s"
pkg_proto="/usr/5bin/pkgproto -c"
pkg_mk="/usr/5bin/pkgmk -o"
pkg_ck="/usr/5bin/pkginfo"

## locations
pkg_loc="/var/spool/pkg"
ports_loc="/usr/ports/"
port_loc="/usr/ports/"$category"/"$pkg""

##
## packaging functions
##
chpkg() {
	#echo "===> Checking package"
	if [ -f "$pkg_loc"/"$pkg"-"$version".pkg ]
	then
		echo "===> "$pkg_loc"/"$pkg"-"$version".pkg successfully created"
	fi
}

mkpkg() {
	mkpkginfo
	mkproto
	echo "===> Creating package"
    	/usr/5bin/pkgmk -o
    	/usr/5bin/pkgtrans -s "$pkg_loc" "$pkg"-"$version".pkg "$pkg"
    	rm -r "$pkg_loc"/"$pkg"
    	rm -r /tmp/"$pkg"
	chpkg
}

mkproto() {
	echo "===> Creating prototype"
	/usr/5bin/pkgproto -c "$category" .=. > prototype
    	sed -i'' '/=/!d' prototype
    	sed -i'' '1d;2d;' prototype
    	sed -i '1s/^/i pkginfo \n/' prototype
}

mkpkginfo() {
	echo "===> Creating pkginfo"
	echo "PKG="$pkg"" >> pkginfo
	echo "NAME="$name"" >> pkginfo
	echo "VERSION="$version"" >> pkginfo
	echo "ARCH="$arch"" >> pkginfo
	echo "CATEGORY="$category"" >> pkginfo
	echo "PSTAMP="$version"" >> pkginfo
	echo "BASEDIR="$basedir"" >> pkginfo
}

extract() {
	echo "===> Extracting archive"
	case "$1" in
		*.tar.bz2|*.tbz2|*.tbz)         tar xvjf "$1" ;;
            	*.tgz)                          tar zxvf "$1" ;;
            	*.tar.gz)                       tar xvzf "$1" ;;
            	*.tar.xz)                       tar xvJf "$1" ;;
            	*.tar)                          tar xvf "$1" ;;
            	*.rar)                          7z x "$1" ;;
            	*.zip)                          unzip "$1" ;;
            	*.7z)                           7z x "$1" ;;
            	*.lzo)                          lzop -d  "$1" ;;
            	*.gz)                           gunzip "$1" ;;
            	*.bz2)                          bunzip2 "$1" ;;
            	*.Z)                            uncompress "$1" ;;
            	*.xz|*.txz|*.lzma|*.tlz)        xz -d "$1" ;;
            	*) echo "'$1' could not be decompressed." ;;
        esac
}

##
## pkg functions
##
envir() {
num=`ls $pkg_loc | grep pkg | wc -l`
inum=`$pkg_ck | wc -l`
echo "
No. of Stream Packages (*.pkg) in cache: "$num"
No. of Installed Packages:               "$inum"
Package cache location:                  $pkg_loc
SVR4 package tools:                      $pkg_add
                                         $pkg_rm
                                         $pkg_proto
                                         $pkg_trans
"
}

usage() {
echo "usage: pkg [command] [argument]

Available commands:
search  (-s)  - searches the repository [TODO]
install (-i)  - installs SVR4 package
update  (-u)  - updates packages [TODO]
remove  (-r)  - uninstalls a package but does not delete it from cache
delete  (-d)  - deletes package from cache and system
sync    (-sy) - sync with repository [TODO]
list    (-l)  - list all installed packages
verify  (-vf) - verify hashes of packages
env     (-e)  - outputs pkg environment and package cache details
ver     (-v)  - check pkg version
help    (-h)  - outputs this message"
}

##
## pkg
##
case "$1" in
	install*|-i*|update*|-u*|remove*|-r*|delete*|-d*|sync*|-sy*)
        # using heirloom tools to check for root
    	id=`id | awk -F'=' '{print $2}' | awk -F'(' '{print $1}'`
        if [ "$id" != 0 ]
        then
        	echo "You must be root"
        	exit 1
    	elif [ "$id" = 0 ]
        then
		case "$1" in
			install*|-i*)
				if [ "$2" > 0 ]
				then
            				ver=`ls "$pkg_loc" | grep "$2" | tail -n1`
            				/usr/5bin/pkgadd -d "$pkg_loc"/"$ver"
				else
					echo "You must specify a package name"
					exit 1
				fi				
				;;
            		update*|-u*)
            			echo "TODO"
            		;;
			remove*|-r*)
				"$pkg_rm" "$2"
			;;
            		delete*|-d*)
            			rm "$pkg_loc"/"$2"-*.pkg
            		;;
            		sync*|-sy*)
            			echo "TODO"
            		;;
		esac
	fi
	;;
    	search*|-s*)
    	echo "TODO"
    	;;
    	list*|-l*)
    	"$pkg_ck"
    	;;
    	help*|-h*)
    	usage
    	;;
    	verify*|-vf*)
		if [ "$2" = '' ]
		then
			echo "You must specify a package"
			exit 1
		elif [ "$2" != '' ]
		then
		sha256sum "$pkg_loc"/"$2"-*.pkg
		fi
    	;;
    	env*|-e*)
	envir
    	;;
    	ver*|-v*)
    	/usr/5bin/pkginfo -x pkg
    	;;
esac
