#!/usr/5bin/sh

##
## pkgbuild builds ports from their mkport files
##

. /usr/bin/pkg

usage() {
	echo "usage: pkgbuild category/port"
}

id=`id | awk -F'=' '{print $2}' | awk -F'(' '{print $1}'`
if [ "$id" != 0 ]
then
	echo "You must be root"
        exit 1
elif [ "$id" = 0 ]
then
	cd "$ports_loc""$1"
        ./mkport
else
        usage
fi

