#!/sbin/sh

. /usr/bin/pkg

pkg=help2man
version=1.47.8
category=doc
arch="x86_64"
basedir="/"
pstamp="$version"
name="generates man pages"
source="http://ftp.gnu.org/gnu/help2man/help2man-1.47.8.tar.xz"

mkdir -p /tmp/"$pkg"

wget "$source"
# heirloom tar doesn't work with tar xz files
/bin/tar xJf "$pkg"-"$version".tar.xz

cd "$pkg"-$version

./configure \
	--prefix=/usr/local \
	--mandir=/usr/local/man \
	--disable-nls
make
make DESTDIR=/tmp/"$pkg" install

cd /tmp/"$pkg"
mkpkg

