#!/bin/sh

. /usr/bin/pkg

pkg=nvi
version="1.81.6"
category=editors
arch="x86_64"
basedir="/"
pstamp="$version"
name="ex-vi clone"
source="http://harrier.slackbuilds.org/misc/$pkg-$version.tar.bz2"

mkdir -p /tmp/"$pkg"

wget "$source"
/bin/tar xf "$pkg"-"$version".tar.bz2

cd "$pkg"-$version

# Apply patches to eliminate bogus "DB_CREATE must be specified to create databases.
patch -p1 < $CWD/nvi.diffs
patch -p1 < ../nvi.diffs $CWD
cd build.unix
../dist/configure \
    --prefix=/usr/local \
    --enable-widechar \
    --disable-static \
    --program-prefix="n"
make -j1
make -j1 install DESTDIR=/tmp/$pkg

mkpkg

